AppQuality/unguess-react

src/common/components/BugDetail/BugStateDropdown.tsx, src/common/components/BugDetail/Priority.tsx, src/common/components/BugDetail/Tags.tsx, src/features/api/apiTags.ts, src/pages/Bug/Actions.tsx, src/pages/Bugs/Content/BugPreview.tsx
🔨 refactor(Actions.tsx): remove unnecessary refetch prop from BugTags component
🔨 refactor(BugPreview.tsx): remove unnecessary refetch prop from BugTags component
=> Refactor-preview-main-features

src/pages/Video/Content.tsx, src/pages/Video/components/ObservationForm.tsx, src/pages/Video/components/Player.tsx, src/pages/Video/components/Transcript.tsx
🚀 feat(Transcript): add appTheme import for styling in Transcript component
=> New-video-player

package.json, src/pages/Bug/Chat.tsx, src/pages/Video/PageHeader.tsx, src/pages/Video/components/ObservationTooltip.tsx, src/pages/Video/components/Player.tsx, src/pages/Video/components/Transcript.tsx, src/pages/Videos/Metas.tsx, src/pages/Videos/PageHeader.tsx, yarn.lock
=> Additional fixes 

package.json, src/features/api/apiTags.ts, src/pages/Video/components/Player.tsx, yarn.lock
This pull request fixes an issue where patch observations were causing unnecessary re-renders. The issue has been resolved by making changes to the code logic.
=> Fix patch observation re-render issue

src/constants.ts, src/pages/Campaign/pageHeader/Meta/index.tsx, src/pages/Video/index.tsx, src/pages/Videos/index.tsx
Tagging tool functionality flag:
- The user cannot see the GoToVideoList button in the campaign dashboard.
- User is redirected to the notFound page if they try to directly access the videos page (/campaigns/ID/videos) or the single video page (/campaigns/ID/videos/ID)
=> Tagging tootl Feature flag

src/assets/icons/placeholder-video.svg, src/pages/Videos/parts/VideoItem.tsx
🔧 refactor(VideoItem.tsx): update ThumbnailContainer styles and add PlaceholderVideo component
=> 🎨 add(placeholder-video.svg): add placeholder video SVG icon

src/common/schema.ts, src/features/api/apiTags.ts, src/features/api/index.ts, src/pages/Video/Actions.tsx, src/pages/Video/PageHeader.tsx, src/pages/Video/components/ConfirmDeleteModal.tsx, src/pages/Video/components/Observation.tsx, src/pages/Video/components/ObservationForm.tsx, src/pages/Video/components/Player.tsx, src/pages/Video/components/Transcript.tsx, src/pages/Videos/Metas.tsx, src/pages/Videos/parts/VideoItem.tsx, src/pages/Videos/types.ts, src/pages/Videos/useVideos.ts, src/pages/Videos/utils/getSeverityTagsWithCount.tsx
🔀 refactor(apiTags.ts): update endpoint names for video observations
🔀 refactor(index.ts): update endpoint names for videos in API
🔀 refactor(Video/Actions.tsx): update API query hooks for video endpoints
🔨 refactor(PageHeader.tsx): update function names for fetching video data
🔨 refactor(ConfirmDeleteModal.tsx): update function names for deleting videos
🔨 refactor(Observation.tsx): update types for video observations
🔨 refactor(ObservationForm.tsx): update types for video observations
🔨 refactor(Player.tsx): update function names for video operations
🔨 refactor(Transcript.tsx): update function names for video operations
🔨 refactor(Metas.tsx): update function names for fetching campaign videos
🔨 refactor(VideoItem.tsx): update types for campaign videos
🔨 refactor(types.ts): update types …
=> 🔀 refactor(common/schema.ts): update paths for videos in API schema

src/pages/Campaign/pageHeader/Meta/index.tsx, src/pages/Dashboard/headerContent.tsx, src/pages/Dashboard/projectPageHeader.tsx, src/pages/Video/components/Player.tsx, src/pages/Video/index.tsx, src/pages/Videos/index.tsx
🔧 fix(Player.tsx): add missing imports and hooks for navigation and localization
=> Improve-feature-flag-check

src/pages/Video/components/ObservationTooltip.tsx, src/pages/Video/components/Transcript.tsx
🔨 refactor(Transcript.tsx): adjust position calculation in Transcript component
=> Fix-transcript-obs-button

package.json, yarn.lock
=> 🔺 chore(package.json): update unguess-design-system dependency to v31.101

src/pages/Videos/Content.tsx, src/pages/Videos/parts/InfoRow.tsx, src/pages/Videos/useVideos.ts
🔧 fix(useVideos.ts): update type definition for CampaignVideos array
=> 🔨 refactor(Content.tsx): simplify InfoRow component props and usage

src/pages/Video/components/TitleDropdown.tsx
🔧 chore(TitleDropdown.tsx): update MediaFigure style to prevent flex shrink
=> 🔨 refactor(TitleDropdown.tsx): adjust style properties for Menu component

src/pages/Video/components/ObservationTooltip.tsx, src/pages/Video/components/Player.tsx
🔨 refactor(Player.tsx): remove unnecessary setIsPlaying and video play calls
=> FIX(ObservationTooltip.tsx): fix seekPlayer function call duplication

src/pages/Videos/parts/InfoRow.tsx
=> FIX(InfoRow.tsx): remove uc description in accordion

src/pages/Video/components/Player.tsx, src/pages/Video/components/Transcript.tsx
Refactor the Player and Transcript components to improve code readability and maintainability. Add a new optional parameter `forcePlay` to the `setCurrentTime` function in the Transcript component, allowing the player to start playing when seeking to a specific time.
=> Refactor Player and Transcript components

src/pages/Dashboard/CampaignItem.tsx, src/pages/Dashboard/SuggestedCampaigns.tsx, src/pages/Dashboard/campaigns-list/list.tsx, src/pages/Dashboard/project-items/list.tsx
This pull request fixes issues with hooks drilling and onClick behavior in the CampaignCard component. It reduces the number of hooks used and fixes the onClick function to correctly navigate to the campaign dashboard.
=> Reduce hooks drilling and fix onClick issues in CampaignCard

src/pages/Insights/Collection/ObservationCard.tsx
use 'title' tag value for card header title
=> Observation-lightbox

src/pages/Insights/Collection/ObservationCard.tsx, src/pages/Insights/Collection/components/CardGrid.tsx, src/pages/Insights/InsightsDrawer/InsightForm.tsx, src/pages/Insights/InsightsDrawer/components/ButtonsFooter.tsx
🔨 refactor(CardGrid.tsx): remove explicit grid-template-rows property
=> Fix-observation-card

src/pages/Insights/InsightsDrawer/InsightForm.tsx, src/pages/Insights/InsightsDrawer/index.tsx
🔧 refactor(InsightsDrawer/index.tsx): add scroll reset on editing mode change
=> Fix-insight-form

src/features/api/api.ts, src/features/api/apiTags.ts, src/features/bugsPage/severityFilter.ts, src/features/uxFilters/clusterFilter.ts, src/features/uxFilters/severityFilter.ts, src/pages/Campaign/useWidgets/Experience/useUxData.tsx, src/pages/Campaign/useWidgets/Experience/widgets/Insights/filters/FiltersTags.tsx, src/pages/Campaign/useWidgets/Experience/widgets/Insights/filters/useFilterData.ts, src/pages/Campaign/useWidgets/Experience/widgets/Insights/utils.tsx
🔨 refactor(FiltersTags.tsx): remove unused getSeverity import and function call
=> Fix-campaign-insights

src/pages/Campaign/pageHeader/Meta/index.tsx
hasTaggingToolFeature and totalVideos count
=> 🔧 refactor(Meta/index.tsx): update condition to show InsightsIcon based on

src/pages/Insights/Collection/ObservationCard.tsx
🎨 style(ObservationCard.tsx): update flex properties for better layout in ObservationCard
=> 🔧 chore(ObservationCard.tsx): adjust tag size and add margin to StyledTag

src/pages/Insights/Collection/components/AccordionSection.tsx, src/pages/Insights/Collection/components/CardGrid.tsx
🔨 refactor(AccordionSection.tsx): adjust grid-gap size to theme.space.sm
🎨 style(AccordionSection.tsx): update background color and box-shadow logic
🔨 refactor(AccordionSection.tsx): remove unnecessary style prop in AccordionSection
🎨 style(CardGrid.tsx): update background color, border-radius, and padding
=> 🚀 feat(AccordionSection.tsx): add Divider component import

src/pages/Insights/InsightsDrawer/InsightForm.tsx
🎨 style(InsightForm.tsx): add marginBottom to ObservationCard component
=> 🎨 style(InsightForm.tsx): add marginBottom to InsightForm container

src/pages/Insights/InsightsDrawer/index.tsx
🎨 style(InsightsDrawer/index.tsx): improve spacing and alignment in InsightsDrawer
=> 🔧 fix(InsightsDrawer/index.tsx): adjust styling and layout in InsightsDrawer

src/features/templates/Page.tsx
=> forced all pages to show english version

src/pages/Dashboard/Modals/CreateProjectModal.tsx, src/pages/Dashboard/index.tsx, src/pages/Dashboard/projectPageHeader.tsx
=> refactor: update GTM event names to 'workspaces-action'

src/common/components/navigation/sidebar/index.tsx, src/features/campaigns/index.ts, src/pages/Dashboard/campaigns-list/useArchivedCampaigns.tsx, src/pages/Dashboard/campaigns-list/useCampaignsGroupedByProject.tsx, src/pages/Dashboard/filters/test.tsx, src/pages/Dashboard/filters/utils.tsx, src/pages/Dashboard/index.tsx
Introduce archive functionality for campaigns and projects, enhance navigation, and update related UI components. Improve filtering and state management for archived campaigns, along with necessary translations and alerts.
=> Add campaign archiving functionality and UI updates

package.json, src/pages/Bugs/Content/BugPreview.tsx, src/pages/ExpressWizard/drawer.tsx, src/pages/ExpressWizard/index.tsx, yarn.lock
- update ds version
- minor fixes
=> Bump-ds-version

src/common/components/navigation/workspacesDropdown/index.tsx, src/pages/Dashboard/Modals/CreateProjectModal.tsx, src/pages/Dashboard/index.tsx, src/pages/Dashboard/projectPageHeader.tsx, src/pages/ExpressWizard/drawer.tsx, src/pages/ExpressWizard/index.tsx
- update analytics express
- fix workspace management analytics
=> release-20250205

src/locales/en/translation.json, src/locales/it/translation.json, src/pages/ExpressWizard/steps/express-1/whereApp.tsx, src/pages/ExpressWizard/steps/express-1/whereWeb.tsx, src/pages/ExpressWizard/steps/express-1/who.tsx, src/pages/ExpressWizard/steps/express-2/whereApp.tsx, src/pages/ExpressWizard/steps/express-2/whereWeb.tsx, src/pages/ExpressWizard/steps/express-2/who.tsx, src/pages/ExpressWizard/steps/express-3/whereApp.tsx, src/pages/ExpressWizard/steps/express-3/whereWeb.tsx, src/pages/ExpressWizard/steps/express-3/who.tsx, src/pages/ExpressWizard/steps/express-4/whereApp.tsx, src/pages/ExpressWizard/steps/express-4/whereWeb.tsx, src/pages/ExpressWizard/steps/express-4/who.tsx
UI fixes for express campaigns:
added red asterisk to required fields,
added default selection on RadioCards
=> Un 776 express UI fixes

src/pages/ExpressWizard/steps/express-3/who.tsx, src/pages/ExpressWizard/steps/express-4/who.tsx
Modify the age range to include '55+' in the WhoStep component.
=> Update age range in WhoStep component

src/pages/ExpressWizard/index.tsx
Introduce an environment indicator to the ExpressWizardContainer, distinguishing between staging and production environments.
=> Add environment indicator to ExpressWizardContainer

src/pages/ExpressWizard/index.tsx
Enhance the error handling mechanism for API requests to provide clearer feedback and improve user experience during failures.
=> Improve error handling for API requests

src/common/campaigns/index.ts
Replace hardcoded API URL with a base URL that adapts based on the environment, improving flexibility and maintainability.
=> Refactor API URL to use environment-specific base URL

src/pages/Plan/ModulesList.tsx, src/pages/Plan/index.tsx, src/pages/Plan/modules/Age.tsx, src/pages/Plan/modules/Gender.tsx, src/pages/Plan/modules/Goal.tsx, src/pages/Plan/modules/InstructionsNote.tsx, src/pages/Plan/modules/Language.tsx, src/pages/Plan/modules/Literacy.tsx, src/pages/Plan/modules/OutOfScope.tsx, src/pages/Plan/modules/SetupNote.tsx, src/pages/Plan/modules/TargetNote.tsx, src/pages/Plan/modules/Users.tsx, src/pages/Plan/modulesMap.tsx
Refactor the ModulesList component to utilize dynamic module mapping, enhancing modularity and maintainability. Introduce new modules, including Age, Gender, Goal, and others, while updating the MODULES_BY_TAB configuration accordingly.
=> Refactor ModulesList for dynamic module mapping and add new modules

src/locales/en/translation.json, src/locales/it/translation.json, src/pages/Dashboard/Counters.tsx, src/pages/Dashboard/Project.tsx, src/pages/Dashboard/SuggestedCampaigns.tsx, src/pages/Dashboard/hooks/useCampaignsAndPlans.ts, src/pages/Dashboard/hooks/useProjectPlans.ts
Introduce new modules for tasks, age, gender, and digital literacy, along with improved validation and error handling. Refactor existing components for better structure and responsiveness. Update API types and enhance UI elements for a more cohesive user experience. Add end-to-end tests for new functionalities and improve existing test coverage.
=> UN-989: improve page header counter with also plans

src/pages/Plan/ModulesList.tsx
Enhance the visibility logic for modules by conditionally rendering them based on their availability, ensuring only visible modules are displayed.
=> Improve visibility handling for modules in ModulesList component

src/pages/Plan/Controls.tsx, src/pages/Plan/summary/components/DetailsCard.tsx
Introduce approval functionality to the Controls and DetailsCard components, allowing users to approve plans directly from the interface. This update improves user interaction by enabling status updates and navigation based on plan approval status.
=> Enhance Controls and DetailsCard components with approval functionality

src/pages/Plan/ModulesList.tsx, src/pages/Plan/modules/Tasks/parts/TaskItem.tsx, src/pages/Plan/modules/Tasks/parts/TasksList.tsx, src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx, src/pages/Plan/modules/Tasks/parts/nav/TasksListNav.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointItem.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointItemDesktop.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointItemSmartphone.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointItemTablet.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointWeb.tsx, src/pages/Plan/modules/Touchpoints/parts/TouchpointsList.tsx, src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointItemNav.tsx, src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointsListNav.tsx, src/pages/Plan/navigation/aside/NavItemChildren.tsx
https://unguess.atlassian.net/browse/UN-1029
=> UN-1029-module-tasks-fixes

src/pages/Plan/modals/SendRequestModal.tsx, src/pages/Plan/modules/Tasks/parts/modal/DeleteTaskConfirmationModal.tsx, src/pages/Plan/modules/Touchpoints/parts/modal/DeleteTouchpointConfirmationModal.tsx, src/pages/Plan/modules/modal/DeleteModuleConfirmationModal.tsx
=> refactor(plan): restructure DeleteModuleConfirmationModal footer with FooterItem components

src/pages/Plan/ModulesList.tsx, src/pages/Plan/common/StickyCol.tsx
Ref: https://unguess.atlassian.net/browse/UN-1132
=> fix: adjust sticky column height and add scroll spacer to ModulesList

src/common/components/PlanCreationInterface/ProjectDropdown.tsx, src/common/components/PlanCreationInterface/index.tsx, src/pages/Dashboard/LaunchCampaignCards.tsx, src/pages/Dashboard/index.tsx, src/pages/Dashboard/project-items/list.tsx, src/pages/Dashboard/project-items/table.tsx, tests/api/projects/_post/200_Example_1.json, tests/api/projects/_post/request_Example_1.json, tests/api/projects/pid/campaigns/_get/200_Example_Project_Campaigns.json, tests/api/workspaces/wid/projects/_get/200_Example_1.json, tests/api/workspaces/wid/projects/pid/_get/200_Example_Project.json, tests/e2e/dashboard.spec.ts, tests/e2e/project.spec.ts, tests/fixtures/components/PlanCreationInterface.ts, tests/fixtures/components/PromoList.ts, tests/fixtures/pages/Dashboard.ts, tests/fixtures/pages/Project.ts
- pre populate project id if opened from project page
- fix UN-1136 autocomplete cannot create new project
- fix service tiles not working inside projects
=> UN-1136-project-creation

src/pages/Templates/index.tsx, tests/e2e/templates/index.spec.ts, tests/fixtures/pages/Templates.ts
=> fix: remove access check for viewing templates when handling errors

src/pages/Plan/ModulesList.tsx, src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx, src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointItemNav.tsx, src/pages/Plan/navigation/aside/NavItem.tsx
Resolves:
- UN-1113: error border color to red900
- UN-1048: white background on cards in focus
=> Fixes to aside nav

src/features/navigation/Navigation.tsx
=> Remove 'templates' case from sidebar dispatch logic

src/pages/Plan/PlanBody.tsx, src/pages/Plan/common/NavContainer.tsx, src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx, src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointItemNav.tsx, src/pages/Plan/navigation/aside/AddBlockButton.tsx, src/pages/Plan/navigation/aside/NavItem.tsx, src/pages/Plan/navigation/aside/NavItemChildren.tsx
=> fix: adjust padding and margin in various components for improved layout

src/locales/en/translation.json, src/pages/JoinPage/Steps/Step1.tsx
Revise the signup form to include a link to the privacy policy alongside the terms and conditions.
=> Update terms and conditions link to include privacy policy

src/pages/Video/components/TitleDropdownNew.tsx
=> fix: edit listboxAppendToNode from Autocomplete component

src/common/components/ServiceTiles/index.tsx, src/pages/Dashboard/SuggestedCampaigns.tsx, src/pages/Dashboard/project-items/Plans.tsx, src/pages/Plan/common/ModulesBottomNavigation.tsx
…estedCampaigns, Plans, and ModulesBottomNavigation components
=> release-candidate

src/pages/Plan/Controls/index.tsx, src/pages/Plan/context/planContext.tsx, tests/e2e/plan/draft.spec.ts
feat: add a save plan configuration step in request quotation handling in Controls component and update related tests
=> UN-1766 save plan configuration

src/analytics.ts, src/common/Track.tsx, src/common/analytics-plugins/userpilot.ts, src/pages/JoinPage/useJoinSubmit.tsx
Store the UTM source in sessionStorage for analytics tracking and enhance Userpilot token management by simplifying the token handling and improving the loaded state check.
=> Store UTM source and improve Userpilot token handling
