AppQuality/unguess-react

package.json, src/pages/Video/components/Transcript.tsx, src/pages/Videos/PageHeader.tsx, yarn.lock
🔥 refactor(PageHeader.tsx): remove unused appTheme import
=> Transcript-add-obs-button

src/common/schema.ts, src/features/api/index.ts, src/locales/en/translation.json, src/locales/it/translation.json, src/pages/Video/Actions.tsx, src/pages/Videos/Content.tsx, src/pages/Videos/useVideos.ts
- return only form-factor in [ Desktop, Tablet, Smartphone, Other ]
- if the form factor is smart-tv, null, or not in [ pc-desktop, tablet, smartphone ] return "Other"
=> Fix api device 

src/pages/Video/components/Player.tsx
The code changes in `Player.tsx` update the URL handling in the video player component. Instead of directly using `video.url`, the code now checks if `video.streamUrl` is available and uses it as the URL if present, falling back to `video.url` otherwise. This change improves the flexibility of the video player and allows for better integration with different video sources.
=> "Update video player URL handling"

package.json, src/assets/icons/play-fill.svg, src/pages/Video/components/ParagraphMeta.tsx, src/pages/Video/components/Player.tsx, src/pages/Video/components/Transcript.tsx, yarn.lock
This pull request updates the dependency on @appquality/unguess-design-system from version 3.1.101 to version 3.1.102 in the package.json file. The update includes bug fixes and improvements to the design system. Keeping our dependencies up to date ensures compatibility and allows us to take advantage of the latest features and fixes
This pull request updates the video player URL handling in the `Player.tsx` component. Instead of directly using `video.url`, the code now checks if `video.streamUrl` is available and uses it as the URL if present, falling back to `video.url` otherwise. This change improves the flexibility of the video player and allows for better integration with different video sources.
Additionally, a play button has been added to the transcript in the `ParagraphMeta.tsx` …
=> Improve player and transcript usability

src/pages/Video/components/Player.tsx
The z-index value in Player.tsx has been updated from 3 to 101. This change improves the stacking order of the Player component, ensuring it appears above other elements on the page.
=> Update z-index value of PlayerContainer

src/hooks/useLocalizeDashboardUrl.ts
This pull request adds a feature flag for the tagging tool in the `useLocalizeDashboardUrl.ts` file. It also includes a new hook `useFeatureFlag` to check if the feature flag is enabled. This change allows for conditional rendering of the dashboard route based on the presence of the tagging tool feature flag.
=> Add feature flag for tagging tool in useLocalizeDashboardUrl.ts

src/pages/Insights/Collection/components/AccordionSection.tsx, src/pages/Insights/Collection/components/UsecaseSection.tsx, src/pages/Insights/utils/getSeverityColor.ts
metadata and Tag in Grape component
=> Fix-grapes

src/common/schema.ts, src/features/api/index.ts, src/features/navigation/Navigation.tsx
The Navigation component has been updated to handle the preference value as a string instead of a number. This change ensures compatibility with the API endpoint that expects a string value. Additionally, the `settingValue` property in the Navigation component has been updated to parse the preference value as an integer using `Number.parseInt()`. These changes improve the reliability and consistency of the Navigation component when handling user preferences.
=> Refactor Navigation component to handle preference value as string

src/features/navigation/Navigation.tsx
This pull request adds the `disableMenuLanguageSettings` option to the navigation feature. This option allows the user to disable the language settings menu in the navigation component.
=> Add disableMenuLanguageSettings option to navigation

src/pages/Insights/Collection/components/UsecaseSection.tsx
The UsecaseSection component has been refactored to handle cases where there is no data to display. Previously, the component would render an empty section, but now it returns null when both the memoizedGrapes and ungrouped arrays are empty. This improves the code by reducing unnecessary rendering and improves the user experience by not displaying empty sections.
=> Refactor UsecaseSection component to handle empty data

src/common/components/inviteUsers/projectSettings.tsx
Revise the invite message in project settings to accurately reflect the current user count.
=> Update project settings invite message for user count

src/pages/Campaign/useWidgets/Report/ReportRow.tsx
This pull request includes a small change to the `src/pages/Campaign/useWidgets/Report/ReportRow.tsx` file. The change improves the display of the report title by adding a `span` with `overflowWrap: 'anywhere'` to handle long titles more gracefully.
* [`src/pages/Campaign/useWidgets/Report/ReportRow.tsx`](diffhunk://#diff-9a17758ed6a97fa75c34679886f44cd8e883bbb9197bc121e8b049db4757d22dR139-R141): Added a `span` with `overflowWrap: 'anywhere'` around the `report.title` to improve the handling of long titles.
=> fix: Update column size in ReportRow for better responsiveness

src/pages/Service/SingleServicePageHeader.tsx
Streamline the handling of service duration by directly using the `duration_in_days` property, improving clarity and reducing unnecessary calculations.
It's now an optional info that can be ignored setting to 0 directy in strapi definition (currently only TA has this field set to 0).
=> Refactor duration handling in SingleServicePageHeader component

src/features/api/index.ts, src/pages/ExpressWizard/mapToCampaignFields.tsx
Refactor language handling to use string representations instead of numeric IDs and add new API endpoints for campaign suggestions.
Closes UN-476.
=> Update dossier language format in Express API

src/features/campaigns/index.ts, src/features/campaignsFilter/campaignsFilterSlice.ts, src/pages/Dashboard/campaigns-list/useArchivedCampaigns.tsx, src/pages/Dashboard/campaigns-list/useCampaignsGroupedByProject.tsx, src/pages/Dashboard/emptyState.tsx, src/pages/Dashboard/filters/index.tsx, src/pages/Dashboard/filters/test.tsx, src/pages/Dashboard/filters/type.tsx
Replace the testNameId with a testType object in the campaign filters, enhancing the filter functionality and improving code clarity.
=> Refactor campaign filters to use testType object instead of testNameId

src/pages/Dashboard/const.ts, src/pages/Dashboard/projectPageHeader.tsx
Eliminate the Jotform URL and associated feature flag logic to streamline the ProjectPageHeader component. This change simplifies the code and removes unnecessary dependencies.
=> Remove Jotform URL and feature flag logic from ProjectPageHeader

src/pages/ExpressWizard/index.tsx
With this fix the confirmation modal is only shown during the steps and not in the thank you page.
Now if you click on close in the thank you page you'll have the same behavior as clicking the "Go to project" CTA.
=> fix: handle close for thank you page

src/common/components/ScrollingGrid.tsx, src/common/components/ServiceTiles/index.tsx, src/pages/Dashboard/SuggestedCampaigns.tsx
Math.ceil arrotonda sempre per eccesso il valore garantendo la validità del check se mostrare o meno la freccia destra/sinistra
=> fix: fix ScrollingGrid navigation arrows

src/pages/Campaign/pageHeader/EditableTitle.tsx, src/pages/Dashboard/EditableDescription.tsx, src/pages/Dashboard/EditableTitle.tsx, src/pages/Dashboard/projectPageHeader.tsx
Add the preventEmpty prop to the InputToggle component in the EditableTitle component. This ensures that the input value cannot be empty. The change helps improve the user experience by preventing the submission of empty values.
fix: Update EditableDescription component
Create a new EditableDescription component that allows users to edit the project description. The component includes an InputToggle with a placeholder and a character limit of 64. The component also handles the onBlur event to update the project description via an API call. If the API call fails, an error notification is displayed.
fix: Update EditableTitle component
Create a new EditableTitle component that allows users to edit the project title. The component includes an InputToggle with a character limit of 64. The …
=> feat: Add preventEmpty to InputToggle in EditableTitle component

src/pages/ExpressWizard/index.tsx
Update the campaign call in ExpressWizardContainer to use 'goal' instead of 'testDescription' for clarity.
=> Rename testDescription to goal in ExpressWizardContainer campaign call

src/pages/Dashboard/SuggestedCampaigns.tsx
Ensure the SuggestedCampaigns component returns null when there are no plans or campaigns to display, preventing unnecessary rendering.
=> Handle empty plans and campaigns in SuggestedCampaigns component

src/pages/Dashboard/hooks/useCampaignsAndPlans.ts, src/pages/Dashboard/hooks/useProjectPlans.ts
Change the orderBy parameter from start_date to lastUpdate for improved sorting of campaigns and project plans.
=> Update orderBy parameter to use lastUpdate for campaigns and project plans

src/pages/Plan/Controls.tsx, src/pages/Plan/summary/components/ConfirmationCard.tsx, tests/e2e/plan/pending_review.spec.ts, tests/fixtures/Plan.ts
Update the ConfirmationCard component to reset the submission state after a draft status update. Add a data-qa attribute to the confirm activity button for improved testability. Update tests to reflect these changes.
=> Ensure submission state resets and add data-qa attribute for confirm button

src/pages/Plan/modules/TargetSize.tsx
This pull request includes several changes to the `TargetSize` component in the `src/pages/Plan/modules/TargetSize.tsx` file. The most important changes include removing an unused import, updating the `FormField` component's styling, and simplifying the error handling logic.
* Removed the unused import of `InfoIcon` from the `src/assets/icons/info-icon.svg` file.
* Updated the `FormField` component to remove the inline `marginBottom` style.
* Simplified the error handling logic by removing the conditional rendering of the `InfoIcon` and associated message when there is no error. [[1]](diffhunk://#diff-6b20956ee1d03e3f43ed962fed1598e665096c389edde1bbdb918374b77703b4L118-R117) [[2]](diffhunk://#diff-6b20956ee1d03e3f43ed962fed1598e665096c389edde1bbdb918374b77703b4L128-L134)
=> UN-1037 removed info message and icon from targetsize

src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx, src/pages/Plan/navigation/aside/NavBody.tsx, src/pages/Plan/navigation/aside/NavItem.tsx
This pull request includes minor changes to the formatting of task and navigation item displays in the `src/pages/Plan` module.
Formatting adjustments:
* [`src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx`](diffhunk://#diff-14bf84fa152f4f52c4b65763391d4a36292e52da9b6fc06a6f38ab88d58ff73dL86-R86): Added a space after the task number for improved readability.
* [`src/pages/Plan/navigation/aside/NavItem.tsx`](diffhunk://#diff-5dd0c890b8ac5a11054f6e4ad74da75e74635d4eeeda83e67bcf9a4a0695100aL83-R83): Removed the task number and adjusted the bold styling to only apply to the module title.
=> UN-1042 fix: remove numbering from module titles in aside navigation

src/features/navigation/Navigation.tsx
This pull request includes a minor change to the `Navigation` component in the `src/features/navigation/Navigation.tsx` file. The change removes redundant code that closes the sidebar when the 'templates' case is encountered, as this action is already handled in other cases. 
Codebase simplification:
* [`src/features/navigation/Navigation.tsx`](diffhunk://#diff-e9240292d73f667d69b58fba444826035d6f7eb444d33a6cabf6985f3b7bf391L108-L109): Removed the redundant `dispatch(setSidebarOpen(false));` and `break;` statements in the 'templates' case.
=> UN-1036: fix closed sidebar on "templates" click

src/pages/Bugs/Content/BugsTable/components/SingleGroupAccordion.tsx
This pull request includes a small adjustment to the `SingleGroupAccordion` component in `SingleGroupAccordion.tsx`. The change modifies the bug count displayed in the "see all" text to subtract 3 from the total number of bugs.
=> UN-626: adjust displayed bug count in SingleGroupAccordion

src/locales/en/translation.json, src/pages/Dashboard/project-items/Plans.tsx, src/pages/Dashboard/project-items/index.tsx
**Also fixes: UN-1102 and UN-1103**
This pull request introduces updates to improve the user interface text, enhance the display of item counts in a button label, and standardize spacing in the project items dashboard. Below is a summary of the key changes:
* Updated the text for the `_PROJECT_PAGE_PLANS_GROUP_SEE_ALL` key in `src/locales/en/translation.json` to "View more" for better alignment with user expectations.
* Modified the `Plans` component in `src/pages/Dashboard/project-items/Plans.tsx` to dynamically append the count of additional items (beyond the preview limit) to the "View more" button label, improving clarity for users.
* Adjusted the `marginTop` property in the `ProjectItems` component in `src/pages/Dashboard/project-items/index.tsx` to use the `appTheme.space.xxl` …
=> UN-1264: Fix plans view more behaviour
